apiVersion: v1
kind: Service
metadata:
  name: prime-video-clone-service
  namespace: prime-video-clone
  labels:
    app: prime-video-clone
spec:
  type: LoadBalancer
  selector:
    app: prime-video-clone
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http