name: Destroy Server using Terraform
on:
  workflow_dispatch:

jobs:
  create-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Amazon CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4
          terraform_wrapper: false

      - name: Destroy Terraform Configuration
        working-directory: ./terraform-code/sonar
        run: terraform destroy -auto-approve

      - name: Commit Terraform State
        working-directory: ./terraform-code/sonar
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add terraform.tfstate terraform.tfstate.backup
          git commit -m "Update Terraform state [skip ci]" || echo "No changes to commit"
          git push