name: 03 CD EKS Infra Mgmt
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - create
          - destroy

jobs:
  manage-eks-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Amazon CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4
          terraform_wrapper: false

      - name: Initialize Terraform
        working-directory: ./terraform-code/eks-infra
        run: terraform init

      - name: Apply Terraform Configuration
        if: ${{ github.event.inputs.action == 'create' }}
        working-directory: ./terraform-code/eks-infra
        run: terraform apply -auto-approve

      - name: Destroy Terraform Configuration
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: ./terraform-code/eks-infra
        run: terraform destroy -auto-approve

      - name: Commit Terraform State
        working-directory: ./terraform-code/eks-infra
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add terraform.tfstate terraform.tfstate.backup
          git commit -m "Update EKS Terraform state after ${{ github.event.inputs.action }} [skip ci]" || echo "No changes to commit"
          git push