name: CI - Amazon Prime Video Clone
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

env:
  SONAR_HOST_URL: 'http://35.154.134.145:9000'
  SONAR_TOKEN: 'squ_19113af742460f5c5210f11aa1ad66fe3d33b70d'
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REPO_NAME: 'prime-video-clone'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Sonar Scan
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL}}
        uses: SonarSource/sonarqube-scan-action@v2  
        with:
          args: >
            -Dsonar.projectKey=prime-video-clone
            -Dsonar.projectName=prime-video-clone
            -Dsonar.sources=.
            -Dsonar.qualitygate.wait=true

      - name: Install dependencies
        run: npm install

      - name: Trivy FileSystem Scan
        run: trivy fs . > trivy.txt

      - name: Build Docker Image
        run: docker build -t ${ECR_REPO_NAME} .

      - name: Save Trivy Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy.txt
          retention-days: 1

      - name: Setup Amazon CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Create ECR Repository (if missing)
        run: |
          aws ecr describe-repositories --repository-names ${ECR_REPO_NAME} \
          || aws ecr create-repository --repository-name ${ECR_REPO_NAME}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 \
          | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com

      - name: Tag Docker Image
        run: |
          docker tag ${ECR_REPO_NAME} ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${ECR_REPO_NAME}:${{ github.run_number }}
          docker tag ${ECR_REPO_NAME} ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${ECR_REPO_NAME}:latest

      - name: Push Docker Images
        run: |
         docker push ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${ECR_REPO_NAME}:${{ github.run_number }}
         docker push ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${ECR_REPO_NAME}:latest


      - name: Cleanup Docker Images
        run: |
          docker rmi ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${ECR_REPO_NAME}:${{ github.run_number }}
          docker rmi ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${ECR_REPO_NAME}:latest
          docker images