name: Amazon Prime Video Clone CI/CD Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:
    # inputs:
    #   ecr_name:
    #     description: 'Enter the ECR repo name'
    #     required: true
    #     default: 'prime-video-clone'
    #   aws_account_id:
    #     description: 'Enter your AWS Account ID'
    #     required: true
    #     default: '123456789012'

env:
  SONAR_SERVER_URL: 'http://sonarqube.example.com:9000'
  SONAR_TOKEN: ''

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # - name: Sonar Scan
      #   uses: SonarSource/sonarqube-scan-action@v2
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ vars.SONAR_SERVER_URL}}

      # - name: SonarQube Quality Gate
      #   uses: SonarSource/sonarqube-quality-gate-action@v1
      #   env:
      #     SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ env.SONAR_SERVER_URL }}

      - name: Install dependencies
        run: npm install

      # - name: Build Docker image
      #   run: |
      #     IMAGE_TAG=$(git rev-parse --short HEAD)
      #     docker build -t ${{ github.event.inputs.aws_account_id }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ github.event.inputs.ecr_name }}:$IMAGE_TAG .

      # - name: Log in to Amazon ECR
      #   env:
      #     AWS_REGION: 'ap-south-1'
      #   run: |
      #     aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ github.event.inputs.aws_account_id }}.dkr.ecr.$AWS_REGION.amazonaws.com

      # - name: Push Docker image to ECR
      #   env:
      #     AWS_REGION: 'ap-south-1'
      #   run: |
      #     IMAGE_TAG=$(git rev-parse --short HEAD)
      #     docker push ${{ github.event.inputs.aws_account_id }}.dkr.ecr.$AWS_REGION.amazonaws.com/${{ github.event.inputs.ecr_name }}:$IMAGE_TAG
   
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: sivavek
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build docker image and push to dockerhub
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: |
      #       sivavek/prime-video-clone:latest
      #       sivavek/prime-video-clone:${{ github.sha }}